### ISSUE TITLE
App 개발 빌드 배포 방법 논의

### ISSUE THREAD

**Issue by daclouds** [daclouds/soda#17]
지난 회의 때 얘기한 것처럼 
용량 문제로 Github Actions 를 계속 활용 할 수 없고
private repository 를 사용하다 보니 collaborators 에도 제한이 있다.

방법은 여러 가지가 있겠지만
수동으로 배포한다면 주기 별로 담당자를 지정 하는 건 어떨까 한다.

**Comment by hees-k** [comment]
마일스톤이나 스프린트 정해지면, 그 주기로 빌드해서 soda 서버에 올리는건 어떨까요? 서버 재시작 되면 사라지나요?

**Comment by daclouds** [comment]
> 마일스톤이나 스프린트 정해지면, 그 주기로 빌드해서 soda 서버에 올리는건 어떨까요? 서버 재시작 되면 사라지나요?

사라지지 않게 하는 방법이 있을텐데 그 보단
모바일 빌드를 확인 할 수 있는 건 모바일 개발자들이고
서버에 업로드 할 수 있는 건 서버 개발자들이라
누가 올려야 할지 애매하기도 하고
만약 upload 할 수 있는 API 를 만들거나 한다고 해도
방식에 대한 논의가 필요 할 것 같아요.

전 google drive 같은데 공유 폴더 만들어서 올리는 방법을 생각해 보았습니다. :-)
