### ISSUE TITLE
설정 변경이 원활하게 이뤄지지 않는다.

### ISSUE THREAD

**Issue by daclouds** [daclouds/soda#21]
여러 번 시도해야 하거나 (설정은 바꼈는데) 갱신이 바로 안되는 이슈가 있다.

**Comment by hees-k** [comment]
https://github.com/daclouds/soda-mobile/pull/23

선호시간대 1개에 대한 update는 지난번에 수정 반영했고,
push 알림 수신 동의 업데이트 처리 수정 합니다.

현재는 세팅에서 변경 가능한 부분은 선호시간대 1개와 push 동의 on/off 입니다.
