### ISSUE TITLE
20200308 회의

### ISSUE THREAD

**Issue by daclouds** [daclouds/soda#25]
진행자 선정,
서기? 지정하여
회의록을 남겨 보면 어떨까?

**Comment by yoppiii** [comment]
1. 프로젝트 지원자
- 디자인: 후보자 2명 대상으로 답신 대기중. 모집공고는 일단 Close 한다.
- 기획: 후보자 인원에 대해 일단 @yoppiii 가 컨택진행

2. 프로젝트 진행관련
- 매칭종료에 대한 고민 필요
- 튜토리얼은 없음
- 후기관련 항목은 차 후 개발, 매칭 Flow 최대한 간결하게. → 초기 개발 Target은 최대한 심플하게
- 회원관리 Flow, Facebook 가져오기 #기획 정리 후 진행

3. 필요(진행) 업무
- 마일스톤관리 담당 @yoppiii : 금주중 작성 추진. 시간보다는 Task 중심으로 작성.
- QA담당자 지정: Splint 하나 끝날때 쯤. 최초담당 @daclouds 진행
- 신규메시지(종 부분), 매칭이력(환경설정) 추가 @daeunk3 
- 채팅구현 진행 #개발
- 프로젝트들 간의 링크 걸기
- 채팅 채널 구현관련 오류 개선 점검 → 3/12 8시 회의진행
- App 개발 배포 (ios 빌드 추가) @daclouds  
- 백로그 관리 @yoppiii 
- 이슈, 백로그 각차 체크하여 관리 필요 (All)
- 틈틈히 시장조사 추진 (All)
- 앱 아이콘 사이즈 맞춰서 업로드 @daeunk3
