### ISSUE TITLE
socket.io-client (nodejs) sample code

### ISSUE THREAD

**Issue by daclouds** [daclouds/soda#38]
gist 또는 편한 방법으로 공유해 주세요~

**Comment by DongsuDanielLim** [comment]
socket.io web client test
https://gist.github.com/DongsuDanielLim/01f4b59c10b3b64462f594eca14c70b0

카톡방에 공유드렸으나 여기에 한 번 더 기록 차 남깁니다.
코드 상단에 client setting 방법 추가했습니다.
