### ISSUE TITLE
서버 배포 프로세스

### ISSUE THREAD

**Issue by pitachips** [daclouds/soda#42]
ㅇ 배포주기
ㅇ 배포시점
ㅇ 브랜치전략과 배포전략

**Comment by pitachips** [comment]
### 제안

- 정기배포 주기: 격주
  - 예외1) fix 패치: 크리티컬 버그가 발생한 경우 등 
  - 예외2) fast-try 배포: 신규 feature 도입, API 변경, 프론트와 싱크가 필요한 경우 등 
- 정기배포 시점 :  회의가 없는 주의 주말(금~일)
- 정기배포 담당 : 1) 격주 회의에서 담당자를 결정; 2) 담당자는 배포완료 후 카톡에 공지
- 정기배포 버저닝 : 
  - 실서비스 론칭 전 : 실서비스 v1 배포를 위한 사전작업이라는 취지에서 `v1_날짜[_패치번호]` 형식으로 배포 (예시 : v1_20200411 -> 당일 버그픽스 -> v1_20200411_1 -> 며칠 뒤 fix 패치 -> v1_20200413 -> 며칠 뒤 fast-try 배포 -> v1_20200415 -> 당일 버그픽스 -> v1_20200415_1)
  - 실서비스 론칭 시 : 1) 실서버는 최초 1.0.0 버전으로 릴리즈하고 semver를 따른다; 2) 개발 릴리즈는 `v1_날짜[_패치번호]`와  `v2_날짜[_패치번호]` 를 함께 운영

- 브랜치관리
  - 실서비스 론칭 전 :  현재 서버는 개발 서버라고 할 수 있으므로, develop브랜치를 기준으로 PR 및 Release 태깅을 한다.
  - 실서비스 론칭 시 : 1) 실서버와 개발서버 분리; 2) 실서버는 master브랜치에서 배포하고, 개발서버는 develop브랜치에서 배포한다.
  - 개인 작업 브랜치는 hj/doc-amazing-update, ds/feat-awesome-function 포맷을 따른다.

cf. 실서비스 정기배포 관리 : 브랜치관리 방식을 유지하되, 실서비스 론칭 전에 다시 논의한다.

**Comment by pitachips** [comment]
@DongsuDanielLim 제안입니다. 수정의견 달아주세요~ 다른 제안 올리셔도 좋습니다

**Comment by DongsuDanielLim** [comment]
근본적으로 Git Pull 을 사용해서 Server deploy 를 한다면 pm2 deploy 를 써보는건 어떨까요?

https://pm2.keymetrics.io/docs/usage/deployment/
ecosystem file 에 각 env 별 script 와 target host 를 지정하고 pm2 command 로 deploy 가능합니다.
원리는 ecosystem 에서 지정한 repo 에서 git pull 하는 것과 같습니다.
다만 target host 에서 git repo에 접근 하능하도록 ssh key를 등록해야 하고,
forever 에서 pm2 로 server script 를 실행해야 합니다.

**Comment by DongsuDanielLim** [comment]
```
실서비스 론칭 전 : 현재 서버는 개발 서버라고 할 수 있으므로, develop브랜치를 기준으로 PR 및 Release 태깅을 한다.
```
위에 말씀처럼 `develop to master`  pull request 를 보고 결정하면 될 것 같습니다. pull request 를 만든 사람이 배포를 하는건 어떨까요?

**Comment by pitachips** [comment]
> ```
> 실서비스 론칭 전 : 현재 서버는 개발 서버라고 할 수 있으므로, develop브랜치를 기준으로 PR 및 Release 태깅을 한다.
> ```
> 
> 위에 말씀처럼 `develop to master` pull request 를 보고 결정하면 될 것 같습니다. pull request 를 만든 사람이 배포를 하는건 어떨까요?

- 네 pr 만든사람이 배포하는 것 좋은거같아요. 근데 pr을 여러명, 여러번 할 수 있으니 그런때에는 정기회의 때 다음주 배포할 사람을 미리 정하면 어떨까요?

- 그리고 이번주는 제가 내일 배포하도록 할게요~

**Comment by pitachips** [comment]
> 근본적으로 Git Pull 을 사용해서 Server deploy 를 한다면 pm2 deploy 를 써보는건 어떨까요?
> 
> https://pm2.keymetrics.io/docs/usage/deployment/
> ecosystem file 에 각 env 별 script 와 target host 를 지정하고 pm2 command 로 deploy 가능합니다.
> 원리는 ecosystem 에서 지정한 repo 에서 git pull 하는 것과 같습니다.
> 다만 target host 에서 git repo에 접근 하능하도록 ssh key를 등록해야 하고,
> forever 에서 pm2 로 server script 를 실행해야 합니다.

좋습니다~ 서버 이사가기 전후로 적용하면 좋을것같네요
