### ISSUE TITLE
notion.so 사용 검토

### ISSUE THREAD

**Issue by daclouds** [daclouds/soda#47]

**Comment by hees-k** [comment]
앱 소개페이지, 회의록 등 wiki 성격의 것들은 notion이 전체 멤버가 쓰기에 수월할 것 같습니다.
notion이 달력,칸반 등 다양한 형태의 view를 가지고 있어서, 문서/메모 작성 용으로는 더 나을 것 같아요.

GitHub에 있는 kanban도 옮기면 좋을 것 같으나, 불편할 것 같으면 개발자만 사용해도 될거 같아요.
개발 칸반도 notion으로 해보고, 불편하면 다시 돌아오는 것도 한 방법입니다.

개인 의견입니다.

**Comment by pitachips** [comment]
의견입니다.
- 개발 관련된 것은 github이 워낙 잘되어있어서 github 기능을 이용해 관리하는 것이 좋을 것 같습니다. ex) 칸반, issue관리, 개발 관련된 토론, 등등
- 단, 비개발자도 알아야 하는 개발관련 사항은 각 사항마다 노션에 1~3줄 이내로 적어두거나 링크를 걸어두면 좋을 것 같아요. 서버의 예를 들자면 릴리즈현황 혹은 릴리즈 링크, 각 릴리즈마다 변경된 주요내용 혹은 change.md로의 링크, 깃허브 wiki로의 주제별 링크 를 노션에 걸어둘 수 있을 거 같습니다. 개인적으로는 링크를 걸어두는 것으로 충분할 거 같네요.
