### ISSUE TITLE
구현된 서버 API 모두 postman에 등록/수정 요청

### ISSUE THREAD

**Issue by hees-k** [daclouds/soda#7]

**Comment by DongsuDanielLim** [comment]
Postman Collection을 어떻게 공유드리면 될까요?
 - Postman Team
 - Collection export

**Comment by hees-k** [comment]
Postman 이미 쓰고 있어요. pitachips님한테 초대해달라고 하셔야 될거 같아요.
https://soda-server.postman.co/

작업하다가 이름이 알아보기 어려워서 제가 이름 바꿔두고 좀 추가하고 했어요. 근데 서버에 얼마나 어떻게 구현되어 있는지 몰라서 정리 한번은 필요할 것 같아요.

Postman 괜찮은 기능 많은거 같던데, pitachips님이랑 얘기 해보시고 편하신 대로 관리 하시면 될 것 같아요.
따로 export는 필요 없고, team으로 보면 될거 같아요.

**Comment by KimHeeSeok** [comment]
PUT /match 로 매칭요청을 하고 있던대요.  매칭 취소는 어떻게 하나요?

**Comment by DongsuDanielLim** [comment]
`https://soda-server.postman.co/collections/4958004-665be898-cf43-41ad-9208-e8a0770f208c?version=latest&workspace=281d1c4f-2d41-4584-89b5-eca2367c1382#158646a4-73a9-451e-88a9-c39421520a2f`

변동사항이 있으면 도큐먼트에 반영되도록 할게요.
